Improve documentation
ushahidi/platform pull request #4093
Opened 2020-10-09 11:50 UTC by UdokaVrede

This pull request makes the following changes:
-

Test checklist:
- [ ]

- [ ] I certify that I ran my checklist

Fixes ushahidi/platform# .

Ping @ushahidi/platform

2020-10-09 14:09 UTC, UdokaVrede commented
> [clabot:check]

[clabot:check]

2020-10-09 15:17 UTC, rowasc requested changes
This is fantastic, thank you <3 I left a couple of very small requests, then we can merge

2020-10-09 15:17 UTC, rowasc commented on CONTRIBUTING.md
> +- **Documentation**: if you find an area of the Ushahidi platform that could use better docs, we would love to hear from you in an issue, and would be seriously excited if you send a [Pull Request](h
hey so this is totally not your fault, but could we change "non-technically" to "without knowing how to code" ? or just "...get involved if you are passionate...."  without mention of technical-ity :D 
Writing is a technical skill, and docs are tough, and I don't want folks to feel like their contribution is less technical or less valued <3

2020-10-09 15:17 UTC, rowasc commented on docs/contributors-to-ushahidi.md
> +This is a list of people who have contributed to Ushahidi. Not everyone in this list contributed in code. Some folks here are designers, and they designed different components of the Ushahidi platfor
keep code singular (it's a difference in writing style only but it's the one we tend to use)

2020-10-10 21:43 UTC, rowasc approved these changes
LGTM! Thanks for the quick turnaround on applying feedback !

2020-10-10 21:46 UTC, merged

2020-10-10 21:49 UTC, rowasc commented
@allcontributors please add @UdokaVrede for docs

2020-10-12 07:44 UTC, UdokaVrede commented
Hi @rowasc can I go ahead to reading and improving the docs